spring:
  datasource:
    #                url: jdbc:mysql://${jiebao.datasource.ip}:3306/jpms?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    #                username: ${jiebao.datasource.username}
    #                password: ${jiebao.datasource.password}
    url: jdbc:mysql://127.0.0.1:3306/inform?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  #文件上传大小限制
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  #静态资源
  resources:
    static-locations: classpath:/static/   ,file:D:/jpms/jpmsupload/picture/

  #session 3小时
  server:
    session:
      timeout: 10800

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jiebao.information.model
  global-config:
    db-config:
      id-type: auto



pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  autoRuntimeDialect: trues


server:
  port: 9999